name: Linux CI

on:
  push:
    branches: [ "devel", "main" ]
  pull_request:
    branches: [ "devel", "main" ]
  workflow_dispatch:

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v7
      with:
        submodules: true

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: '6.11.*'

    - name: Configure CMake
      id: configuration
      run: cmake -B ${{github.workspace}}/build
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_INSTALL_PREFIX=/usr
        -DCMAKE_INSTALL_LIBDIR=lib

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Install
      env:
        DESTDIR: ${{github.workspace}}/RiffTree-v${{steps.configuration.outputs.config_version}}-x86_64.AppDir
      run: cmake --install build --config ${{env.BUILD_TYPE}}

    - name: Upload Artifacts
      env:
        INSTALL_LOCATION: RiffTree-v${{steps.configuration.outputs.config_version}}-x86_64.AppDir
      uses: actions/upload-artifact@v7
      with:
        name: ${{env.INSTALL_LOCATION}}
        path: ${{github.workspace}}/${{env.INSTALL_LOCATION}}
        retention-days: 90
        overwrite: true
